//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AcadLib.Model.Utils.Tabs.History.Db
{
    using System;
    using System.Collections.Generic;
    
    public partial class StatEvents
    {
        public int Id { get; set; }
        public string App { get; set; }
        public string CompName { get; set; }
        public string Departament { get; set; }
        public string Division { get; set; }
        public string DocName { get; set; }
        public string DocPath { get; set; }
        public string EventName { get; set; }
        public int EventTimeSec { get; set; }
        public string FIO { get; set; }
        public System.DateTime Finish { get; set; }
        public double FinishSizeMb { get; set; }
        public string SerialNumber { get; set; }
        public System.DateTime Start { get; set; }
        public string UserName { get; set; }
        public string Version { get; set; }
    }
}
